### ISSUE TITLE
[BUGFIX] correct on-screen navigation

### ISSUE THREAD

**Issue by russsharek** [realsirjoe/remindcal#1]
I was working on an OpenBSD package for remindcal, and I noticed that the onscreen display for the left and right navigation keys was reversed. Here's a one-line patch that corrects it.

Really nice tool. Thank you for letting us play with it!

[onscreen_navigation_bugfix.patch](https://github.com/realsirjoe/remindcal/files/14029903/onscreen_navigation_bugfix.patch)

**Comment by realsirjoe** [comment]
thank you for the patch, its fixed now!

**Comment by russsharek** [comment]
Hooray!

Would you mind tagging a new release? I know it's a minor fix, but having a specific version to target makes packaging so much easier.

On January 24, 2024 5:23:13 PM EST, sirjoe ***@***.***> wrote:
>Closed #1 as completed.
>

-- 
Cheers,
Russ Sharek
Director, Circus Freaks
https://circusfreaks.org
214-494-0952

**Comment by realsirjoe** [comment]
Sure I tagged it now, thanks for your contribution!

**Comment by russsharek** [comment]
Thank you!

FYI, my port was accepted!

Remindcal will appear in OpenBSD's ports collection starting with the upcoming 7.5 release.
